# Generated by Django 3.2.15 on 2023-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
        ),
    ]
